# # # Welcome to Jekyll! # # #

# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

# # # Site Settings # # #

title           : "RodFireProductions"
subtitle        : # Site tagline
description     : "Just another dead inside artist's portfolio website."
url             : "https://deadinsideartist.art"
favicon         : "../assets/images/skullfavicon.png"
meta_image      : "https://i.ibb.co/6rFsTzv/banner-meta.png"
noise_img       : "../assets/images/noisetexture.png"
logo            : # Path to logo
style           : "../assets/dead.css"
script          : "../assets/dead.js"  #"../assets/scripts/itsme.js"

marshalllee     : "../assets/images/marshalllee.gif"
marshalllee2    : "../assets/images/marshalllee2.gif"

repository      : "https://github.com/RodFireProductions/RodFireProductions.github.io"

date_format     : "%b %-d, %Y"

markdown        : kramdown
highlighter     : rouge


# # # Site Author / Owner # # #
author_name        : "Rodrick \"RodFireProductions\""
author_pronouns    : "they/them"
author_title       : "Your Nonbinary Demigod"
author_avatar      : "../assets/images/avatar_trans1.png" #"../assets/images/avatar.png"
author_location    : "Hell"
author_email       : "rodrick@deadinsideartist.art"

# # # Social Links # # #
links:
    website     : "https://deadinsideartist.art"

    twitter     : "https://twitter.com/rodfire8181"

    instagram   : "https://www.instagram.com/rodfireproductions/"

    github      : "https://github.com/RodFireProductions"

    itch        : "https://rodfireproductions.itch.io/"

    deviantart  : "https://deviantart.com/rodfireproductions"

    kofi        : "https://ko-fi.com/rodfireproductions"

    steam       : "https://steamcommunity.com/id/rodfire8181"

    youtube     : "https://www.youtube.com/channel/UC9x1ux5Qw09CmKCngIFy7kw"

    linktree    : "https://linktr.ee/rodfireproductions"

    carrd       : "https://deadinsideartist.carrd.co/"

    gumroad     : "https://rodfireproductions.gumroad.com/"


widgets:

    kofi        : "<script type='text/javascript' src='https://storage.ko-fi.com/cdn/widget/Widget_2.js'></script><script type='text/javascript'>kofiwidget2.init('Support Me on Ko-fi', 'var(--purp_bg)', 'R6R34PDMQ');kofiwidget2.draw();</script>"

    picarto     : "<img href='https://api.picarto.tv/channel/name/RodFire8181/status.png'>"

itch:

    meetchalice : '<iframe frameborder="0" src="https://itch.io/embed/1201338?bg_color=000000&amp;fg_color=f6acf1&amp;link_color=2ce8f4&amp;border_color=bebebe" width="552" height="167"><a href="https://rodfireproductions.itch.io/meet-chalice3">Meet Chalice&lt;3 by RodFireProductions</a></iframe>'
    meetchalice2: '<iframe frameborder="0" src="https://itch.io/embed-upload/4469637?color=333333" allowfullscreen="" width="750" height="570"><a href="https://rodfireproductions.itch.io/meet-chalice3">Play Meet Chalice&lt;3 on itch.io</a></iframe>'

# # # Technical stuff # # #

plugins:
  - jekyll-coffeescript
  - jemoji
