# # # Welcome to Jekyll! # # #

# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

# # # Site Settings # # #

title           : "RodFireProductions"
subtitle        : # Site tagline
description     : "Just another dead inside artist's portfolio website."
url             : "https://deadinsideartist.art"
favicon         : "assets/images/skullfavicon.png"
meta_image      : "assets/images/avatar.png"
logo            : # Path to logo
style           : "assets/dead.css"
style2          : "../assets/dead.css"

repository      : "https://github.com/RodFireProductions/RodFireProductions.github.io"

date_format     : "%b %-d, %Y"

# # # Site Author / Owner # # #
author_name        : "Rodrick \"RodFireProductions\""
author_pronouns    : "they/them"
author_title       : "Your Nonbinary Demigod"
author_avatar      : "assets/images/avatar.png"
author_location    : "Hell"
author_email       : "rodrick@deadinsideartist.art"

# # # Social Links # # #
links:
    website     : # "https://example.com"

    twitter     : # "https://twitter.com/"

    instagram   : # "https://instagram.com/"

    github      : # "https://github.com/"

    itch        : # "https://itch.io/"

    deviantart  : # "https://deviantart.com/"

    kofi        : # "https://ko-fi.com/"

    steam       : # "https://steamcommunity.com/id/"

    youtube     : # "https:/youtube.com/channel/"

    linktree    : # "https://linktr.ee/"
