# # # Welcome to Jekyll! # # #

# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

# # # Site Settings # # #

title           : "RodFireProductions"
subtitle        : # Site tagline
description     : "Just another dead inside artist's portfolio website."
url             : "https://deadinsideartist.art"
favicon         : "../assets/images/skullfavicon.png"
meta_image      : "https://i.ibb.co/6rFsTzv/banner-meta.png"
logo            : # Path to logo
style           : "assets/dead.css"
style2          : "../assets/dead.css"

marshalllee     : "../assets/images/marshalllee.gif"
marshalllee2    : "../assets/images/marshalllee2.gif"

repository      : "https://github.com/RodFireProductions/RodFireProductions.github.io"

date_format     : "%b %-d, %Y"

# # # Site Author / Owner # # #
author_name        : "Rodrick \"RodFireProductions\""
author_pronouns    : "they/them"
author_title       : "Your Nonbinary Demigod"
author_avatar      : "../assets/images/avatar.png"
author_location    : "Hell"
author_email       : "rodrick@deadinsideartist.art"

# # # Social Links # # #
links:
    website     : "https://deadinsideartist.art"

    twitter     : "https://twitter.com/rodfire8181"

    instagram   : "https://www.instagram.com/rodfireproductions/"

    github      : "https://github.com/RodFireProductions"

    itch        : "https://rodfireproductions.itch.io/"

    deviantart  : "https://deviantart.com/rodfireproductions"

    kofi        : "https://ko-fi.com/rodfireproductions"

    steam       : "https://steamcommunity.com/id/rodfire8181"

    youtube     : "https://www.youtube.com/channel/UC9x1ux5Qw09CmKCngIFy7kw"

    linktree    : "https://linktr.ee/rodfireproductions"

    carrd       : "https://deadinsideartist.carrd.co/"


# # # Technical stuff # # #

plugins:
  - jekyll-coffeescript
